# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ok < Formula
  desc "A task runner"
  homepage "https://github.com/broothie/ok"
  version "0.1.35"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/broothie/ok/releases/download/v0.1.35/ok_0.1.35_Darwin_arm64.tar.gz"
      sha256 "7c68a2150756583b18c9cc248672feb9b1452b544f8a9ed27f510ece17003549"

      def install
        bin.install "ok"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/broothie/ok/releases/download/v0.1.35/ok_0.1.35_Darwin_x86_64.tar.gz"
      sha256 "bd0d7c3fa5a71e19a7c94e001be54e23881b016e18d43037348b3a673174cd10"

      def install
        bin.install "ok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/broothie/ok/releases/download/v0.1.35/ok_0.1.35_Linux_arm64.tar.gz"
      sha256 "ad66284c3e6ec0d078de3241f5346f44e7ba92d9b683131f320d3396f0804be2"

      def install
        bin.install "ok"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/broothie/ok/releases/download/v0.1.35/ok_0.1.35_Linux_x86_64.tar.gz"
      sha256 "dc8a1b64eb2beb4e36e40e2f5a817169a300484389fc26b26da584416790ba23"

      def install
        bin.install "ok"
      end
    end
  end
end
