# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ok < Formula
  desc "A task runner"
  homepage "https://github.com/broothie/ok"
  version "0.2.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/broothie/ok/releases/download/v0.2.5/ok_0.2.5_Darwin_x86_64.tar.gz"
      sha256 "6357822d4d62c17b6715bde4e0e15a5f24d51ccbe0de42bf85352b937ee7be4c"

      def install
        bin.install "ok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/broothie/ok/releases/download/v0.2.5/ok_0.2.5_Darwin_arm64.tar.gz"
      sha256 "5544c05de4022023913bdacaba857793d6cdb511c1b7da185a5efa1ad4d3979b"

      def install
        bin.install "ok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/broothie/ok/releases/download/v0.2.5/ok_0.2.5_Linux_arm64.tar.gz"
      sha256 "836a3f745b3c6e51dc51bfdc4dc3fe6206ef9999dc6e2c5310dca305482b98dd"

      def install
        bin.install "ok"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/broothie/ok/releases/download/v0.2.5/ok_0.2.5_Linux_x86_64.tar.gz"
      sha256 "b3b7fde20db5fba5209b8b114a0686742e55b702823ee403ab2e9e51bedcb55c"

      def install
        bin.install "ok"
      end
    end
  end
end
