# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ok < Formula
  desc "A task runner"
  homepage "https://github.com/broothie/ok"
  version "0.1.32"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/broothie/ok/releases/download/v0.1.32/ok_0.1.32_Darwin_x86_64.tar.gz"
      sha256 "a0ddec66de8f2e2e8bb70b3cae469ac8afa96fd8ad52993d1b9111c1f234ed3b"

      def install
        bin.install "ok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/broothie/ok/releases/download/v0.1.32/ok_0.1.32_Darwin_arm64.tar.gz"
      sha256 "5275a11b61b3d51752c31a6399951794e269f24c319df013b07707967eae1a88"

      def install
        bin.install "ok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/broothie/ok/releases/download/v0.1.32/ok_0.1.32_Linux_x86_64.tar.gz"
      sha256 "0c2144aa4882e811c6d739cf6328b7ce261ecbb6efbddf5c33e2cfc86b56f40a"

      def install
        bin.install "ok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/broothie/ok/releases/download/v0.1.32/ok_0.1.32_Linux_arm64.tar.gz"
      sha256 "44a929b47bbee6fdab66df77aeb12db60fbf400dcdd9119fdccf72c27bf82977"

      def install
        bin.install "ok"
      end
    end
  end
end
