# This file was generated by GoReleaser. DO NOT EDIT.
cask "ok" do
  name "ok"
  desc "A unified task runner that discovers and executes tasks from multiple build tools."
  homepage "https://github.com/broothie/ok"
  version "0.3.1-rc.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ok"

  on_macos do
    on_intel do
      url "https://github.com/broothie/ok/releases/download/v#{version}/ok_Darwin_x86_64.tar.gz"
      sha256 "f4e78050908275c63134a16d814f0430dac08c968b36bdc45c5e93a2b76613cf"
    end
    on_arm do
      url "https://github.com/broothie/ok/releases/download/v#{version}/ok_Darwin_arm64.tar.gz"
      sha256 "6aaab5cea19a1510cab494b231f6c768f270936bce024fef7e4da24e53b473c3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/broothie/ok/releases/download/v#{version}/ok_Linux_x86_64.tar.gz"
      sha256 "6a2b09836def784dd4a1de8d557510057df744b694acc43fe04673f2763392d1"
    end
    on_arm do
      url "https://github.com/broothie/ok/releases/download/v#{version}/ok_Linux_arm64.tar.gz"
      sha256 "f8f456a848d683e45732cff493988c7b94616dd0735c12086b512d12b502c400"
    end
  end

  # No zap stanza required
end
