# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ok < Formula
  desc "A unified task runner that discovers and executes tasks from multiple build tools."
  homepage "https://github.com/broothie/ok"
  version "0.3.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/broothie/ok/releases/download/v0.3.6/ok_Darwin_x86_64.tar.gz"
      sha256 "840417cffa3f42ae3ef8339648ed51ca771e0e3c59ee14f6c7e4f1948d0b9ce0"

      def install
        bin.install "ok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/broothie/ok/releases/download/v0.3.6/ok_Darwin_arm64.tar.gz"
      sha256 "33930c1651346e7ae9de6b2364e3b8461c2f0390f66a2d8afd4996270c5036fd"

      def install
        bin.install "ok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/broothie/ok/releases/download/v0.3.6/ok_Linux_x86_64.tar.gz"
      sha256 "7c67b493109dde25d5b9c2ab02d98bf160b00ff03570f0cc8799551399b50f13"
      def install
        bin.install "ok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/broothie/ok/releases/download/v0.3.6/ok_Linux_arm64.tar.gz"
      sha256 "65d0e8c96b2dc86dd7416e4e4e7c9a4d22c12e132daae23fa5de5eaf013c74c2"
      def install
        bin.install "ok"
      end
    end
  end
end
