# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ok < Formula
  desc "A unified task runner that discovers and executes tasks from multiple build tools."
  homepage "https://github.com/broothie/ok"
  version "0.3.1-rc.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/broothie/ok/releases/download/v0.3.1-rc.2/ok_Darwin_x86_64.tar.gz"
      sha256 "9be31b560605b4dd9df9cfed2ad4d06a981cb977531fa5dcd154dd8841499ac4"

      def install
        bin.install "ok"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/broothie/ok/releases/download/v0.3.1-rc.2/ok_Darwin_arm64.tar.gz"
      sha256 "099cd181525e238f3203ad2447306fa2e897b5cecbc28b11cf459af90d7e53d9"

      def install
        bin.install "ok"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/broothie/ok/releases/download/v0.3.1-rc.2/ok_Linux_x86_64.tar.gz"
      sha256 "7945cf75f32bb0c6616944387e4fa5cdf77c0721c616b7cdc4c1bf9f58bd5d3a"
      def install
        bin.install "ok"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/broothie/ok/releases/download/v0.3.1-rc.2/ok_Linux_arm64.tar.gz"
      sha256 "6c193eab5dc69f2735b3109f9ae972392e054475521bc71d7ce705ebe4ce0087"
      def install
        bin.install "ok"
      end
    end
  end
end
